# Generated by Django 5.0.6 on 2024-10-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_medicationinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationinfo',
            name='medication_guide',
        ),
    ]
