# Generated by Django 5.0.6 on 2024-10-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_medicationinfo_medication_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mix_medication_name', models.CharField(max_length=100)),
                ('mix_enterprise_name', models.CharField(max_length=100)),
                ('mix_etc_otc_name', models.CharField(max_length=100)),
                ('prohibit_content', models.CharField(max_length=100)),
                ('medication_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicationinfo')),
            ],
        ),
    ]
